name: Build and Deploy Hugo

on:
  push:
    branches: [ main ]  # Deploy when pushing to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.125.0'
        extended: true

    - name: Build Hugo Site
      run: hugo --minify --verbose

    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        server: '31.147.204.99'
        port: 22
        remote_path: '/var/www/app/public_html'
        local_path: './public/*'
        sftp_only: true

