name: Build and Deploy Hugo

on:
  push:
    branches: [ main ]  # Deploy when pushing to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.125.0'
        extended: true

    - name: Build Hugo Site
      run: hugo --minify --verbose

    - name: Deploy via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        protocol: sftp
        port: 22                    
        local-dir: ./public          
        server-dir: /public_html     
        dangerous-clean-slate: false 
