name: Build and Deploy Hugo

on:
  push:
    branches: [ main ]  # Deploy when pushing to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.125.0'
        extended: true

    - name: Build Hugo Site
      run: hugo --minify --verbose

    - name: Deploy to Custom Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        debug: true
        source: "public/*"
        target: "~/public_html"
